name: GitHub Pages

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: macos-10.15
    steps:
      - name: Setup Node
        uses: actions/checkout@master
        with:
          node-version: '14.x'

      - name: Install
        run: yarn install --ignore-optional --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
