version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: update-yarn
          command: "sudo npm install -g yarn@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: setup-github
          command: |
            git config --global user.name sprout2000
            git config --global user.email k_konno1983@yahoo.co.jp
      - run:
          name: deploy
          command: yarn deploy
